apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: cmhr007/ticketing-payments
          imagePullPolicy: Always
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: JWT_SECRET
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGO_URI
              value: "mongodb://payments-mongo-srv:27017/payments"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      port: 4003
      targetPort: 4003
  