name: Deploy-Manifest

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{secrets.DO_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s/prod
