name: "Test-Orders"

on:
  pull_request:
    paths:
      - "orders/**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - run: cd orders && npm install && npm run test:ci
