name: "Test-Tickets"

on: # when to run the workflow
  pull_request: # when a pull request event occurs
    paths: # when the pull request event occurs on the following paths 
      - "tickets/**" # only when the pull request event occurs on the tickets folder
  
jobs: # the jobs to run
  build: # build job
    runs-on: ubuntu-latest # the type of machine to run the job on
    steps: # the steps to run in the job
      - uses: actions/checkout@v3.5.2 # checkout the files in the repo to the runner machine
      - run: cd tickets && npm install && npm run test:ci # install dependencies and run tests
